// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContentCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "content",
		Short:       "Manage content command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newContentListContentCmd(flags))
	cmd.AddCommand(newContentListFailedCountCmd(flags))
	cmd.AddCommand(newContentListFiltersConfigCmd(flags))
	cmd.AddCommand(newContentListHolidaysCmd(flags))
	cmd.AddCommand(newContentListTasksCmd(flags))
	return cmd
}
