// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLibrariesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "libraries",
		Short:       "Manage libraries command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLibrariesListFiltersConfigCmd(flags))
	cmd.AddCommand(newLibrariesListLibrariesCmd(flags))
	return cmd
}
