// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newModerationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "moderation",
		Short:       "Manage moderation command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newModerationListFiltersConfigCmd(flags))
	cmd.AddCommand(newModerationListModerationCmd(flags))
	return cmd
}
