// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newReportsListFiltersConfigCmd(flags *rootFlags) *cobra.Command {
	var flagAvailableReportTypes string
	var flagBrands string
	var flagKeywordGroups string
	var flagModerationStatuses string
	var flagNetworks string
	var flagTags string
	var flagUsers string

	cmd := &cobra.Command{
		Use:         "list-filters-config",
		Short:       "GET /api/reports/filters_config",
		Example:     "  classintercom-pp-cli reports list-filters-config",
		Annotations: map[string]string{"pp:endpoint": "reports.list_filters_config", "pp:method": "GET", "pp:path": "/api/reports/filters_config", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/reports/filters_config"
			params := map[string]string{}
			if flagAvailableReportTypes != "" {
				params["available_report_types"] = formatCLIParamValue(flagAvailableReportTypes)
			}
			if flagBrands != "" {
				params["brands"] = formatCLIParamValue(flagBrands)
			}
			if flagKeywordGroups != "" {
				params["keyword_groups"] = formatCLIParamValue(flagKeywordGroups)
			}
			if flagModerationStatuses != "" {
				params["moderation_statuses"] = formatCLIParamValue(flagModerationStatuses)
			}
			if flagNetworks != "" {
				params["networks"] = formatCLIParamValue(flagNetworks)
			}
			if flagTags != "" {
				params["tags"] = formatCLIParamValue(flagTags)
			}
			if flagUsers != "" {
				params["users"] = formatCLIParamValue(flagUsers)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "reports", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAvailableReportTypes, "available-report-types", "", "")
	cmd.Flags().StringVar(&flagBrands, "brands", "", "")
	cmd.Flags().StringVar(&flagKeywordGroups, "keyword-groups", "", "")
	cmd.Flags().StringVar(&flagModerationStatuses, "moderation-statuses", "", "")
	cmd.Flags().StringVar(&flagNetworks, "networks", "", "")
	cmd.Flags().StringVar(&flagTags, "tags", "", "")
	cmd.Flags().StringVar(&flagUsers, "users", "", "")

	return cmd
}
