// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Attributes struct {
	Address            string `json:"address"`
	AppName            string `json:"app_name"`
	CityAndRegion      string `json:"city_and_region"`
	ExternalProvider   string `json:"external_provider"`
	HasCurrentRollover bool   `json:"has_current_rollover"`
	Id                 int    `json:"id"`
	IsManual           bool   `json:"is_manual"`
	IsSftp             bool   `json:"is_sftp"`
	Name               string `json:"name"`
	Phone              string `json:"phone"`
	Region             string `json:"region"`
	TimeZone           string `json:"time_zone"`
	Type               string `json:"type"`
}

type Attributes2 struct {
	AssociatedUserId int    `json:"associated_user_id"`
	FirstName        string `json:"first_name"`
	FullName         string `json:"full_name"`
	Id               int    `json:"id"`
	LastName         string `json:"last_name"`
	Unlisted         bool   `json:"unlisted"`
}

type Attributes3 struct {
	FirstName string `json:"first_name"`
	Id        int    `json:"id"`
	LastName  string `json:"last_name"`
	Role      string `json:"role"`
	UserTitle string `json:"user_title"`
}

type Attributes4 struct {
	InstituteId   int             `json:"institute_id"`
	InstituteType string          `json:"institute_type"`
	LogoUrl       string          `json:"logo_url"`
	Name          string          `json:"name"`
	Relationships json.RawMessage `json:"relationships"`
}

type Attributes5 struct {
	ArchivedOrArchiveSkipped bool   `json:"archived_or_archive_skipped"`
	EmergencyContactsEnabled bool   `json:"emergency_contacts_enabled"`
	InstituteId              int    `json:"institute_id"`
	InstituteType            string `json:"institute_type"`
	Name                     string `json:"name"`
	QuotaMet                 bool   `json:"quota_met"`
	Status                   string `json:"status"`
}

type Attributes6 struct {
	Groups   json.RawMessage `json:"groups"`
	Parents  json.RawMessage `json:"parents"`
	Sections json.RawMessage `json:"sections"`
	Staff    json.RawMessage `json:"staff"`
	Students json.RawMessage `json:"students"`
	Total    json.RawMessage `json:"total"`
}

type Data struct {
	Attributes Attributes6 `json:"attributes"`
	Id         string      `json:"id"`
	Type       string      `json:"type"`
}

type DataHealthStatData struct {
	Attributes Attributes4 `json:"attributes"`
	Id         string      `json:"id"`
	Type       string      `json:"type"`
}

type DirectoryIncluded struct {
	Attributes    Attributes    `json:"attributes"`
	Id            string        `json:"id"`
	Relationships Relationships `json:"relationships"`
	Type          string        `json:"type"`
}

type DistrictEvent struct {
	AllDay      bool   `json:"allDay"`
	Description string `json:"description"`
	End         string `json:"end"`
	Id          int    `json:"id"`
	Origin      string `json:"origin"`
	Recurring   bool   `json:"recurring"`
	Start       string `json:"start"`
	Summary     string `json:"summary"`
	Title       string `json:"title"`
	Url         string `json:"url"`
}

type Relationships struct {
	SchoolApiCredential    json.RawMessage `json:"school_api_credential"`
	SmartSiteConfiguration json.RawMessage `json:"smart_site_configuration"`
}

type Relationships2 struct {
	Grade   json.RawMessage `json:"grade"`
	Parents json.RawMessage `json:"parents"`
}

type Relationships3 struct {
	LastDataSync json.RawMessage `json:"last_data_sync"`
}

type ReportEmailUser struct {
	Email string `json:"email"`
	Id    int    `json:"id"`
	Name  string `json:"name"`
}

type StaffData struct {
	Attributes Attributes3 `json:"attributes"`
	Id         string      `json:"id"`
	Type       string      `json:"type"`
}

type StaffJson struct {
	Data json.RawMessage `json:"data"`
}

type StudentData struct {
	Attributes    Attributes2    `json:"attributes"`
	Id            string         `json:"id"`
	Relationships Relationships2 `json:"relationships"`
	Type          string         `json:"type"`
}

type StudentsJson struct {
	Data json.RawMessage `json:"data"`
}

type SyncInfoData struct {
	Attributes    Attributes5    `json:"attributes"`
	Id            string         `json:"id"`
	Relationships Relationships3 `json:"relationships"`
	Type          string         `json:"type"`
}

type Total struct {
	Data Data `json:"data"`
}
