// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDistrictsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "districts",
		Short:       "Manage districts command groups",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDistrictsGetAutocompleteCmd(flags))
	cmd.AddCommand(newDistrictsGetClassEventsCmd(flags))
	cmd.AddCommand(newDistrictsGetDataHealthStatsCmd(flags))
	cmd.AddCommand(newDistrictsGetDistrictEventsCmd(flags))
	cmd.AddCommand(newDistrictsGetGroupEventsCmd(flags))
	cmd.AddCommand(newDistrictsGetSchoolEventsCmd(flags))
	cmd.AddCommand(newDistrictsGetStaffJsonCmd(flags))
	cmd.AddCommand(newDistrictsGetStudentsJsonCmd(flags))
	cmd.AddCommand(newDistrictsGetSyncInfoCmd(flags))
	cmd.AddCommand(newDistrictsGetTotalsCmd(flags))
	return cmd
}
