// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSchoolsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "schools",
		Short:       "Manage schools command groups",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSchoolsGetDirectoryCmd(flags))
	cmd.AddCommand(newSchoolsGetReportEmailUsersCmd(flags))
	cmd.AddCommand(newSchoolsGetSchoolEventsCmd(flags))
	return cmd
}
