// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AssignableUser struct {
	AvatarUrl string `json:"avatar_url"`
	Label     string `json:"label"`
	Value     string `json:"value"`
}

type Channel struct {
	AvatarUrl string `json:"avatar_url"`
	BrandId   string `json:"brand_id"`
	Label     string `json:"label"`
	Network   string `json:"network"`
	Value     string `json:"value"`
}

type Channel2 struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Network string `json:"network"`
	Social  bool   `json:"social"`
}

type ContentActivity struct {
	ActivityDate       string          `json:"activity_date"`
	Approvers          json.RawMessage `json:"approvers"`
	Author             string          `json:"author"`
	BrandName          string          `json:"brand_name"`
	Channels           []Channel2      `json:"channels"`
	ComposeMode        string          `json:"compose_mode"`
	ContentType        string          `json:"content_type"`
	HasAttachments     bool            `json:"has_attachments"`
	Id                 string          `json:"id"`
	ImageUrl           string          `json:"image_url"`
	Labels             json.RawMessage `json:"labels"`
	Message            string          `json:"message"`
	NoteCount          int             `json:"note_count"`
	PublishImmediately bool            `json:"publish_immediately"`
	State              string          `json:"state"`
}

type FailedCount struct {
	Count int `json:"count"`
}

type FeedFeedItem struct {
	Actions          json.RawMessage `json:"actions"`
	BrandAvatarUrl   string          `json:"brand_avatar_url"`
	BrandName        string          `json:"brand_name"`
	ChannelId        string          `json:"channel_id"`
	ChannelName      string          `json:"channel_name"`
	ConversationId   string          `json:"conversation_id"`
	Deleted          bool            `json:"deleted"`
	ExternalId       string          `json:"external_id"`
	ExternalLink     string          `json:"external_link"`
	Flagged          bool            `json:"flagged"`
	HasNotes         bool            `json:"has_notes"`
	Hidden           bool            `json:"hidden"`
	Id               string          `json:"id"`
	IsRoot           bool            `json:"is_root"`
	KeywordFlagged   bool            `json:"keyword_flagged"`
	KeywordTerms     json.RawMessage `json:"keyword_terms"`
	Liked            bool            `json:"liked"`
	Media            []Media         `json:"media"`
	Mention          bool            `json:"mention"`
	Network          string          `json:"network"`
	NotesCount       int             `json:"notes_count"`
	ObjectType       string          `json:"object_type"`
	ParentExternalId string          `json:"parent_external_id"`
	PrivateMessage   bool            `json:"private_message"`
	PublishedAt      string          `json:"published_at"`
	Resolved         bool            `json:"resolved"`
	SourceAvatar     string          `json:"source_avatar"`
	SourceInitials   string          `json:"source_initials"`
	SourceName       string          `json:"source_name"`
	SourceProfileUrl string          `json:"source_profile_url"`
	SourceScreenName string          `json:"source_screen_name"`
	Stats            Stats           `json:"stats"`
	Text             string          `json:"text"`
	TimeAgo          string          `json:"time_ago"`
	UserGenerated    bool            `json:"user_generated"`
}

type FiltersConfig struct {
	Labels    json.RawMessage `json:"labels"`
	Libraries json.RawMessage `json:"libraries"`
}

type FiltersConfigAssignee struct {
	Items []Item `json:"items"`
	Label string `json:"label"`
}

type FiltersConfigAvailableReportType struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

type FiltersConfigBrand struct {
	AvatarUrl string `json:"avatar_url"`
	Label     string `json:"label"`
	Value     string `json:"value"`
}

type FiltersConfigBrand2 struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

type FiltersConfigNetwork struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

type FiltersConfigType struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

type Holiday struct {
	Date string `json:"date"`
	Name string `json:"name"`
}

type Item struct {
	AvatarUrl string `json:"avatar_url"`
	Label     string `json:"label"`
	Value     string `json:"value"`
}

type Library struct {
	Items      json.RawMessage `json:"items"`
	Pagination Pagination2     `json:"pagination"`
}

type Media struct {
	AltText        string `json:"alt_text"`
	ArchivedSource string `json:"archived_source"`
	NetworkId      string `json:"network_id"`
	Source         string `json:"source"`
	Type           string `json:"type"`
}

type Moderation struct {
	Activities json.RawMessage `json:"activities"`
	Pagination Pagination      `json:"pagination"`
}

type Pagination struct {
	CurrentPage  int `json:"current_page"`
	RowsPerPage  int `json:"rows_per_page"`
	TotalRecords int `json:"total_records"`
}

type Pagination2 struct {
	CurrentPage  int `json:"current_page"`
	RowsPerPage  int `json:"rows_per_page"`
	TotalRecords int `json:"total_records"`
}

type Params struct {
	Action            string          `json:"action"`
	AuthenticityToken string          `json:"authenticity_token"`
	BrandIds          json.RawMessage `json:"brand_ids"`
	Build             string          `json:"build"`
	ChannelIds        json.RawMessage `json:"channel_ids"`
	Controller        string          `json:"controller"`
	DateRange         string          `json:"date_range"`
	Network           string          `json:"network"`
	Report            string          `json:"report"`
}

type ReportReportRun struct {
	CreatedAt       string `json:"created_at"`
	CreatedBy       string `json:"created_by"`
	CreatedById     string `json:"created_by_id"`
	FinishedAt      string `json:"finished_at"`
	Id              string `json:"id"`
	MainProductUrl  string `json:"main_product_url"`
	Params          Params `json:"params"`
	ProgressCurrent int    `json:"progress_current"`
	ProgressTotal   int    `json:"progress_total"`
	RanAt           string `json:"ran_at"`
	RangeBeginning  string `json:"range_beginning"`
	RangeEnding     string `json:"range_ending"`
	ReportName      string `json:"report_name"`
	State           string `json:"state"`
}

type Stats struct {
	Angry     string `json:"angry"`
	Haha      string `json:"haha"`
	Like      int    `json:"like"`
	LikeCount int    `json:"like_count"`
	Love      string `json:"love"`
	Sad       string `json:"sad"`
	Wow       string `json:"wow"`
}

type Task struct {
	Tasks json.RawMessage `json:"tasks"`
}

type Task2 struct {
	Assignee            string `json:"assignee"`
	AssigneeAvatarUrl   string `json:"assignee_avatar_url"`
	AssigneeId          string `json:"assignee_id"`
	AttachmentCount     int    `json:"attachment_count"`
	BrandId             string `json:"brand_id"`
	BrandName           string `json:"brand_name"`
	CreatedAt           string `json:"created_at"`
	CreatedBy           string `json:"created_by"`
	CreatedByAvatarUrl  string `json:"created_by_avatar_url"`
	HasAttachments      bool   `json:"has_attachments"`
	Id                  string `json:"id"`
	RelatedContentCount int    `json:"related_content_count"`
	Status              string `json:"status"`
	SubtaskCount        int    `json:"subtask_count"`
	Title               string `json:"title"`
}
