// Copyright 2026 Kris Hagel and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"classintercom-pp-cli/internal/cli"
	"classintercom-pp-cli/internal/client"
	"classintercom-pp-cli/internal/cliutil"
	"classintercom-pp-cli/internal/config"
	"classintercom-pp-cli/internal/mcp/cobratree"
	"classintercom-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("binder_list_filters_config",
			mcplib.WithDescription("GET /api/binder/filters_config. Optional: labels, types. Returns array of FiltersConfigType."),
			mcplib.WithString("labels", mcplib.Description("")),
			mcplib.WithString("types", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/binder/filters_config", true, false, nil, []mcpParamBinding{{PublicName: "labels", WireName: "labels", Location: "query"}, {PublicName: "types", WireName: "types", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("channels_list_channels",
			mcplib.WithDescription("GET /api/channels. Optional: scope. Returns array of Channel."),
			mcplib.WithString("scope", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/channels", true, false, nil, []mcpParamBinding{{PublicName: "scope", WireName: "scope", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("content_list_content",
			mcplib.WithDescription("GET /api/content. Optional: page, rows, sort_field (plus 1 more). Returns array of ContentActivity."),
			mcplib.WithNumber("page", mcplib.Description("")),
			mcplib.WithNumber("rows", mcplib.Description("")),
			mcplib.WithString("sort_field", mcplib.Description("")),
			mcplib.WithNumber("sort_order", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/content", true, false, nil, []mcpParamBinding{{PublicName: "page", WireName: "page", Location: "query"}, {PublicName: "rows", WireName: "rows", Location: "query"}, {PublicName: "sort_field", WireName: "sort_field", Location: "query"}, {PublicName: "sort_order", WireName: "sort_order", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("content_list_failed_count",
			mcplib.WithDescription("GET /api/content/failed_count. Optional: count. Returns the FailedCount."),
			mcplib.WithNumber("count", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/content/failed_count", true, false, nil, []mcpParamBinding{{PublicName: "count", WireName: "count", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("content_list_filters_config",
			mcplib.WithDescription("GET /api/content/filters_config. Optional: assignees, labels, statuses (plus 1 more). Returns array of FiltersConfigAssignee."),
			mcplib.WithString("assignees", mcplib.Description("")),
			mcplib.WithString("labels", mcplib.Description("")),
			mcplib.WithString("statuses", mcplib.Description("")),
			mcplib.WithString("users", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/content/filters_config", true, false, nil, []mcpParamBinding{{PublicName: "assignees", WireName: "assignees", Location: "query"}, {PublicName: "labels", WireName: "labels", Location: "query"}, {PublicName: "statuses", WireName: "statuses", Location: "query"}, {PublicName: "users", WireName: "users", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("content_list_holidays",
			mcplib.WithDescription("GET /api/content/holidays. Optional: date_end, date_start. Returns array of Holiday."),
			mcplib.WithString("date_end", mcplib.Description("")),
			mcplib.WithString("date_start", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/content/holidays", true, false, nil, []mcpParamBinding{{PublicName: "date_end", WireName: "date_end", Location: "query"}, {PublicName: "date_start", WireName: "date_start", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("content_list_tasks",
			mcplib.WithDescription("GET /api/content/tasks. Optional: date_end, date_start. Returns the Task."),
			mcplib.WithString("date_end", mcplib.Description("")),
			mcplib.WithString("date_start", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/content/tasks", true, false, nil, []mcpParamBinding{{PublicName: "date_end", WireName: "date_end", Location: "query"}, {PublicName: "date_start", WireName: "date_start", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("libraries_list_filters_config",
			mcplib.WithDescription("GET /api/libraries/filters_config. Optional: labels, libraries. Returns the FiltersConfig."),
			mcplib.WithString("labels", mcplib.Description("")),
			mcplib.WithString("libraries", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/libraries/filters_config", true, false, nil, []mcpParamBinding{{PublicName: "labels", WireName: "labels", Location: "query"}, {PublicName: "libraries", WireName: "libraries", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("libraries_list_libraries",
			mcplib.WithDescription("GET /api/libraries. Optional: page, rows, sort_field (plus 2 more). Returns the Library."),
			mcplib.WithNumber("page", mcplib.Description("")),
			mcplib.WithNumber("rows", mcplib.Description("")),
			mcplib.WithString("sort_field", mcplib.Description("")),
			mcplib.WithNumber("sort_order", mcplib.Description("")),
			mcplib.WithString("states[]", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/libraries", true, false, nil, []mcpParamBinding{{PublicName: "page", WireName: "page", Location: "query"}, {PublicName: "rows", WireName: "rows", Location: "query"}, {PublicName: "sort_field", WireName: "sort_field", Location: "query"}, {PublicName: "sort_order", WireName: "sort_order", Location: "query"}, {PublicName: "states[]", WireName: "states[]", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("moderation_list_filters_config",
			mcplib.WithDescription("GET /api/moderation/filters_config. Optional: brands, labels, states (plus 1 more). Returns array of FiltersConfigBrand2."),
			mcplib.WithString("brands", mcplib.Description("")),
			mcplib.WithString("labels", mcplib.Description("")),
			mcplib.WithString("states", mcplib.Description("")),
			mcplib.WithString("types", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/moderation/filters_config", true, false, nil, []mcpParamBinding{{PublicName: "brands", WireName: "brands", Location: "query"}, {PublicName: "labels", WireName: "labels", Location: "query"}, {PublicName: "states", WireName: "states", Location: "query"}, {PublicName: "types", WireName: "types", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("moderation_list_moderation",
			mcplib.WithDescription("GET /api/moderation. Optional: page, rows, sort_field (plus 2 more). Returns the Moderation."),
			mcplib.WithNumber("page", mcplib.Description("")),
			mcplib.WithNumber("rows", mcplib.Description("")),
			mcplib.WithString("sort_field", mcplib.Description("")),
			mcplib.WithNumber("sort_order", mcplib.Description("")),
			mcplib.WithString("states[]", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/moderation", true, false, nil, []mcpParamBinding{{PublicName: "page", WireName: "page", Location: "query"}, {PublicName: "rows", WireName: "rows", Location: "query"}, {PublicName: "sort_field", WireName: "sort_field", Location: "query"}, {PublicName: "sort_order", WireName: "sort_order", Location: "query"}, {PublicName: "states[]", WireName: "states[]", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("reports_list_filters_config",
			mcplib.WithDescription("GET /api/reports/filters_config. Optional: available_report_types, brands, keyword_groups (plus 4 more). Returns array of FiltersConfigAvailableReportType."),
			mcplib.WithString("available_report_types", mcplib.Description("")),
			mcplib.WithString("brands", mcplib.Description("")),
			mcplib.WithString("keyword_groups", mcplib.Description("")),
			mcplib.WithString("moderation_statuses", mcplib.Description("")),
			mcplib.WithString("networks", mcplib.Description("")),
			mcplib.WithString("tags", mcplib.Description("")),
			mcplib.WithString("users", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/reports/filters_config", true, false, nil, []mcpParamBinding{{PublicName: "available_report_types", WireName: "available_report_types", Location: "query"}, {PublicName: "brands", WireName: "brands", Location: "query"}, {PublicName: "keyword_groups", WireName: "keyword_groups", Location: "query"}, {PublicName: "moderation_statuses", WireName: "moderation_statuses", Location: "query"}, {PublicName: "networks", WireName: "networks", Location: "query"}, {PublicName: "tags", WireName: "tags", Location: "query"}, {PublicName: "users", WireName: "users", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("reports_list_reports",
			mcplib.WithDescription("GET /api/reports. Optional: page, rows, sort_field (plus 1 more). Returns array of ReportReportRun."),
			mcplib.WithNumber("page", mcplib.Description("")),
			mcplib.WithNumber("rows", mcplib.Description("")),
			mcplib.WithString("sort_field", mcplib.Description("")),
			mcplib.WithNumber("sort_order", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/reports", true, false, nil, []mcpParamBinding{{PublicName: "page", WireName: "page", Location: "query"}, {PublicName: "rows", WireName: "rows", Location: "query"}, {PublicName: "sort_field", WireName: "sort_field", Location: "query"}, {PublicName: "sort_order", WireName: "sort_order", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("social_list_feed",
			mcplib.WithDescription("GET /api/social/feed. Optional: page, scope. Returns array of FeedFeedItem."),
			mcplib.WithNumber("page", mcplib.Description("")),
			mcplib.WithString("scope", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/social/feed", true, false, nil, []mcpParamBinding{{PublicName: "page", WireName: "page", Location: "query"}, {PublicName: "scope", WireName: "scope", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("social_list_filters_config",
			mcplib.WithDescription("GET /api/social/filters_config. Optional: features, networks, users. Returns array of FiltersConfigNetwork."),
			mcplib.WithString("features", mcplib.Description("")),
			mcplib.WithString("networks", mcplib.Description("")),
			mcplib.WithString("users", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/social/filters_config", true, false, nil, []mcpParamBinding{{PublicName: "features", WireName: "features", Location: "query"}, {PublicName: "networks", WireName: "networks", Location: "query"}, {PublicName: "users", WireName: "users", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tasks_list_assignables",
			mcplib.WithDescription("GET /api/tasks/assignables. Optional: users. Returns array of AssignableUser."),
			mcplib.WithString("users", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/tasks/assignables", true, false, nil, []mcpParamBinding{{PublicName: "users", WireName: "users", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tasks_list_filters_config",
			mcplib.WithDescription("GET /api/tasks/filters_config. Optional: brands, statuses, users. Returns array of FiltersConfigBrand."),
			mcplib.WithString("brands", mcplib.Description("")),
			mcplib.WithString("statuses", mcplib.Description("")),
			mcplib.WithString("users", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/tasks/filters_config", true, false, nil, []mcpParamBinding{{PublicName: "brands", WireName: "brands", Location: "query"}, {PublicName: "statuses", WireName: "statuses", Location: "query"}, {PublicName: "users", WireName: "users", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tasks_list_tasks",
			mcplib.WithDescription("GET /api/tasks. Optional: page, rows, sort_field (plus 1 more). Returns array of Task2."),
			mcplib.WithNumber("page", mcplib.Description("")),
			mcplib.WithNumber("rows", mcplib.Description("")),
			mcplib.WithString("sort_field", mcplib.Description("")),
			mcplib.WithNumber("sort_order", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/tasks", true, false, nil, []mcpParamBinding{{PublicName: "page", WireName: "page", Location: "query"}, {PublicName: "rows", WireName: "rows", Location: "query"}, {PublicName: "sort_field", WireName: "sort_field", Location: "query"}, {PublicName: "sort_order", WireName: "sort_order", Location: "query"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export CLASSINTERCOM_COOKIES=<your-key>" +
					"\n      See API docs: https://app.classintercom.com" +
					"\n      Run 'classintercom-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API credentials." +
					"\n      Set it with: export CLASSINTERCOM_COOKIES=<your-key>" +
					"\n      See API docs: https://app.classintercom.com" +
					"\n      Run 'classintercom-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export CLASSINTERCOM_COOKIES=<your-key>" +
					"\n      See API docs: https://app.classintercom.com" +
					"\n      Run 'classintercom-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "classintercom-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "classintercom-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "classintercom",
		"description": "Discovered API spec for classintercom",
		"archetype":   "content",
		"tool_count":  18,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion classintercom-pp-cli binary.",
		"auth": map[string]any{
			"type": "cookie",
			"env_vars": []map[string]any{
				{
					"name":        "CLASSINTERCOM_COOKIES",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"docs_url": "https://app.classintercom.com",
		},
		"resources": []map[string]any{
			{
				"name":        "binder",
				"description": "Operations on filters_config",
				"endpoints":   []string{"list_filters_config"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "channels",
				"description": "Operations on channels",
				"endpoints":   []string{"list_channels"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "content",
				"description": "Operations on holidays",
				"endpoints":   []string{"list_content", "list_failed_count", "list_filters_config", "list_holidays", "list_tasks"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "libraries",
				"description": "Operations on filters_config",
				"endpoints":   []string{"list_filters_config", "list_libraries"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "moderation",
				"description": "Operations on moderation",
				"endpoints":   []string{"list_filters_config", "list_moderation"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "reports",
				"description": "Operations on reports",
				"endpoints":   []string{"list_filters_config", "list_reports"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "social",
				"description": "Operations on filters_config",
				"endpoints":   []string{"list_feed", "list_filters_config"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "tasks",
				"description": "Operations on assignables",
				"endpoints":   []string{"list_assignables", "list_filters_config", "list_tasks"},
				"syncable":    true,
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass page parameter for subsequent pages.",
			"Control page size with the count parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
